### ISSUE TITLE
GETTING WARNING

### ISSUE THREAD

**Issue by zakkyzidan** [someshkar/colabcat#13]
Hi, when i try to install hashcat i get this warning 
https://drive.google.com/file/d/1hjvWM7kv_eBoY-olGlJw3g3SGg2XCKHE/view?usp=sharing
And after a few minutes the runtime is disconnected, how can i solve it?

**Comment by Wingman4l7** [comment]
I would recommend heeding that warning. Google updated the FAQ for free use and now include "password cracking" as "disallowed from Colab runtimes": https://research.google.com/colaboratory/faq.html
