### ISSUE TITLE
And where is the part where you said that this is free ? I am pretty sure it can't be totally free ... or you meant a free trial? 

### ISSUE THREAD

**Issue by minanagehsalalma** [someshkar/colabcat#2]

**Comment by jgamblin** [comment]
Colab is a great tool from Google and free for now. 

```Is it really free to use?
Yes. Colab is free to use.```

https://research.google.com/colaboratory/faq.html

**Comment by minanagehsalalma** [comment]
@jgamblin  hmm that  sounds too good but it's  true .... so what range does the hash rate starts and goes to from your experience with the platform .... even though its  description doesn't sound like it should be used for cracking.

**Comment by OlivierLaflamme** [comment]
@minanagehsalalma @jgamblin its not his project at all. he doesnt know what he is talking about. go to https://github.com/mxrch/penglab for some real help

**Comment by minanagehsalalma** [comment]
> go to https://github.com/mxrch/penglab for some real help. feel free to verify with the commit history. someshkar is a plagiarist

@OlivierLaflamme  Thanks mate

**Comment by someshkar** [comment]
@OlivierLaflamme  I'm sorry if you feel that way, I've commented on the original issue.

**Comment by someshkar** [comment]
@minanagehsalalma yes, Google Colab is a free Jupyter notebook environment intended for Data Science and Machine Learning. The side benefit is practically free access to a really fancy GPU.

**Comment by minanagehsalalma** [comment]
> @OlivierLaflamme I'm sorry if you feel that way, I've commented on the original issue.

@someshkar i don't care about your reply ... you didn't  fork  it ... you  didn't give credit. .. you are a fraud.

**Comment by someshkar** [comment]
@minanagehsalalma I hope you've had a look at the other issue (#3) before saying that, and if you have, you'll know what's up.

**Comment by minanagehsalalma** [comment]
@someshkar no thanks.

**Comment by someshkar** [comment]
@minanagehsalalma if you really don't even want to read the other issue before commenting here, that's on you. I'm closing this issue for now. I hope your Google Colab query got resolved.

**Comment by Jaroneko** [comment]
@minanagehsalalma Please do your own research, as @OlivierLaflamme obviously hasn't. These are two completely independent projects, sharing no code or other assets.

**Comment by axman6** [comment]
Why are security folks such children? @OlivierLaflamme and @minanagehsalalma are jumping straight to conclusions based on no evidence, I’ve only ever seen this behaviour from people in the security community, rarely from software developers. Really makes me not want to branch out into security because if toxic people like this.

**Comment by minanagehsalalma** [comment]
> Why are security folks such children? @OlivierLaflamme and @minanagehsalalma are jumping straight to conclusions based on no evidence, I’ve only ever seen this behaviour from people in the security community, rarely from software developers. Really makes me not want to branch out into security because of toxic people like this.

@axman6 lol dude ... idk why you taking this so serious .... i checked the one olivier linked and it was hella better documented and based on what he said i though that one was the original as its uploaded date much earlier than this.

Stop mentioning me idc about any of this.

**Comment by axman6** [comment]
@minanagehsalalma because you’re spreading the proven wrong claim that this project is plagiarised.

> @someshkar i don't care about your reply ... you didn't fork it ... you didn't give credit. .. you are a fraud

Nice work on the predictably childish reply, you’re bio is a fun read too.

**Comment by minanagehsalalma** [comment]
> you’re bio is a fun read too.

On purpose for sure ;) glad you found it funny. .. 

> @minanagehsalalma because you’re spreading the proven wrong claim that this project is plagiarised.

@axman6 blah blah i don't fuckkin careee 



> Stop mentioning me idc about any of this.

........
