### ISSUE TITLE
Plagerism

### ISSUE THREAD

**Issue by OlivierLaflamme** [someshkar/colabcat#3]
https://github.com/mxrch/penglab 

If you like the project you should simply fork it...

![image](https://user-images.githubusercontent.com/25066959/84212648-6c756e00-aa8c-11ea-9fe7-93e1c75d90a0.png)

You cant be serious.... you should be the one contributing to the project instead of stealing it

**Comment by someshkar** [comment]
I can definitely link to it on the readme.

I didn't think running Hashcat on Colab was something never done before, I just realized that being able to backup and restore sessions when you run into the free limits was a fairly good idea.

Does this help your issue?

**Comment by OlivierLaflamme** [comment]
You definitely should and remove your lenience. Yeah im sure its not something thats never been done. Thats completely besides the point! The point is that you've stolen someone else's code, and might potentially fool people and employers into thinking this is your own. which is reprehensible

**Comment by someshkar** [comment]
I'm really sorry if this got to you, but I really don't know what to say beyond that I'd never seen the other project before, and had been cracking on Colab for more than a year now. I just felt that sharing what I use very often for quickly cracking my neighbour's WPA2 hashes was something worthwhile.

Yes, I'll link to the other project. I'm not deleting the repository because this is my take on doing it, and if you have a look at how  https://github.com/mxrch/penglab does it, you'll realise there's no code stealing at all.

**Comment by Jaroneko** [comment]
> The point is that you've stolen someone else's code

Hold on. Did you actually go so far as to read the code for the two projects before accusing someone of stealing code from another project?

I did. They are absolutely not the same code. The projects have very similar aims, but accomplish this through different actions with slightly differing results and absolutely share no code. It's perfecctly reasonable to assume that both creators have had this idea separately and there's nothing particularly novel in installing hashcat. They just provide means for people to easily do this on Google Colab.

**Comment by Taubin** [comment]
> 
> The point is that you've stolen someone else's code, and might potentially fool people and employers into thinking this is your own **idea** and **code**. which is reprehensible, in other words you're stealing his intellectual property,

Seriously, stealing someone's idea? That's like accusing Pepsi of stealing their idea for a soda from Coke.

**Comment by fluffypony** [comment]
@OlivierLaflamme The code is not even remotely similar, they don't even take the same approach to many of the architectural decisions. Your suggestion that they fork another project should, frankly, be insulting to the developer.

I also think it's absurd to suggest that someone go and perform anything other than a cursory search before embarking on a project like this, and even if they *do* find that someone else has done it before they may choose to redo it from scratch without giving any credit to them.

**Comment by dutyfruit** [comment]
initial project hasen't licence and you add one but why ? Because of the twitter fame ?skldjfikosadhfsdhjkofhdsjkfhjklsdhfkljsdhjfkdshjklfhadjklsfhjkldshfjkadshjk cheh

**Comment by fluffypony** [comment]
@dutyfruit adding a license is recommended by GitHub when you create a new project, and is pretty standard. Also the MIT license is insanely permissive, you can literally take his and sell it for profit without giving him anything. I would be more concerned about a FOSS project being unlicensed.

**Comment by someshkar** [comment]
@fluffypony Yep exactly. GitHub recommends adding a license.

**Comment by axman6** [comment]
@someshkar I recommend you close this issue, it’s clear that @OlivierLaflamme doesn’t know what they’re talking about and hasn’t looked at the code. Nice work on a cool project.

**Comment by someshkar** [comment]
@axman6 Alright then. If everyone's alright with it, I'm closing this issue.
